#!/bin/bash

HISTORY=~/.zsh_history

#Green
COLOR='\033[1;32m'
#Default
DEFAULT='\033[1;37m'

D=`date | cut -d ' ' -f4`
if [ "$D" -lt 10 ]; then
	D="0$D"
fi
M=`date | cut -d ' ' -f2`
if [ "$M" == "Jan" ]; then
	M="01"
elif [ "$M" == "Feb" ]; then
	M="02"
elif [ "$M" == "Mar" ]; then
	M="03"
elif [ "$M" == "Apr" ]; then
	M="04"
elif [ "$M" == "May" ]; then
	M="05"
elif [ "$M" == "Jun" ]; then
	M="06"
elif [ "$M" == "Jul" ]; then
	M="07"
elif [ "$M" == "Aug" ]; then
	M="08"
elif [ "$M" == "Sep" ]; then
	M="09"
elif [ "$M" == "Oct" ]; then
	M="10"
elif [ "$M" == "Nov" ]; then
	M="11"
else
	M="12"
fi
Y=`date | cut -d ' ' -f7`
MYDATE="$COLOR$D/$M/$Y$DEFAULT"
H="$COLOR`date | cut -d ' ' -f5 | cut -d ':' -f1`:`date | cut -d ' ' -f5 | cut -d ':' -f2`$DEFAULT"

echo -e "Bonjour"
echo -e "$COLOR"

#echo -e '     __              __              __            __               ___ _          ___ _  '
#echo -e '    /\ \            /\ \            /\ \          /\ \             / _ \ \        / _ \ \ '
#echo -e '    \ \ \          /  \ \          /  \ \         \ \ \           / //\ \_\      / //\ \_\'
#echo -e '     \ \ \        / /\ \ \        / /\ \ \         \ \ \         | ||| \///     | ||| \///'
#echo -e ' __  /  \ \      / ///\ \ \      /  \ | |||    __  /  \ \        \ \ \          \ \ \     '
#echo -e '/\ \/ /\ \_\    / ///  | |||    /    \/ |||   /\ \/ /\ \_\        \ \_\          \ \_\    '
#echo -e '\ \/ ///\///   / ///   | |||   / /| \__///    \ \/ ///\///    __  | |||     __   | |||    '
#echo -e ' \  ///        \ \ \   / ///  / //| |||        \  ///        /\ \ / ///    /\ \  / ///    '
#echo -e '  \ \ \         \ \ \ / ///   \///| |||         \ \ \        \ \_/ ///     \ \_\/ ///     '
#echo -e '   \ \_\         \ \_/ ///        | |||          \ \_\        \___///       \___ ///      '
#echo -e '    \///          \___///          \|||           \///                                    '

#echo -e '     __                            ___ _                               __________ _ '
#echo -e '    /\ \                          / _ \ \                    _       / _________ \ \'
#echo -e '    \ \ \                        / //\ \ \                  /\ \    | | |      / ///'
#echo -e '     \ \ \              __      / /// \///    ___ _        /  |_|_   \ \ \    / /// '
#echo -e ' __  /  \ \      ___ _ /\ \    / ///         / _ \ \      / /\_ \ \   \ \ \  / ///  '
#echo -e '/\ \/ /\ \_\    / _  \/ ///   / ///         / //\ \ \    / //// ///    \ \ \/ ///   '
#echo -e '\ \/ ///\///   | |||\  ///   / ///         / /// | | |  / //// ///      \ \/ ///    '
#echo -e ' \  ///        | |||/ ///   / ///         / /// / ///  / //// ///        \  ///     '
#echo -e '  \ \ \         \ \/ ///   | | |         | | | / ///   \//// ///         / ///      '
#echo -e '   \ \_\         \  ///     \ \ \         \ \_/ ///       / ///         / ///       '
#echo -e '    \///          \///        \///         \___///        \///          \///        '

#echo -e '.___    .____________                    _____  '
#echo -e '|   | __| _/\_   ___ \  ____   _____    /  |  | '
#echo -e '|   |/ __ | /    \  \/ /  _ \ /     \  /   |  |_'
#echo -e '|   / /_/ | \     \___(  {_} )  Y Y  \/    ^   /'
#echo -e '|___\____ |  \______  /\____/|__|_|  /\____   | '
#echo -e '         \/         \/             \/      |__| '

echo -e " ___    _  ____                _  _   "
echo -e "|_ _|__| |/ ___|___  _ __ ___ | || |  "
echo -e " | |/ _\` | |   / _ \\| '_ \` _ \\| || |_ "
echo -e " | | (_| | |__| (_) | | | | | |__   _|"
echo -e "|___\\__,_|\\____\\___/|_| |_| |_|  |_|  "

echo -e "$DEFAULT"
echo -e "Nous sommes le $MYDATE, il est $H."
echo -e "Vous etes ici : $COLOR`pwd`$DEFAULT"
if [ -f $HISTORY ]; then
	echo -e "Votre derniere commande etait : $COLOR`tail -1 ~/.zsh_history | cut -d ';' -f2`$DEFAULT"
fi
echo ""
echo ""
echo ""
