#!/bin/bash

D=`date | cut -d ' ' -f3`
if [ "$D" -lt 10 ]; then
	D="0$D"
fi
M=`date | cut -d ' ' -f2`
if [ "$M" == "Jan" ]; then
	M="01"
elif [ "$M" == "Feb" ]; then
	M="02"
elif [ "$M" == "Mar" ]; then
	M="03"
elif [ "$M" == "Apr" ]; then
	M="04"
elif [ "$M" == "May" ]; then
	M="05"
elif [ "$M" == "Jun" ]; then
	M="06"
elif [ "$M" == "Jul" ]; then
	M="07"
elif [ "$M" == "Aug" ]; then
	M="08"
elif [ "$M" == "Sep" ]; then
	M="09"
elif [ "$M" == "Oct" ]; then
	M="10"
elif [ "$M" == "Nov" ]; then
	M="11"
else
	M="12"
fi
Y=`date | cut -d ' ' -f6`
H=`date | cut -d ' ' -f4 | cut -d ':' -f1`
Mi=`date | cut -d ' ' -f4 | cut -d ':' -f2`
S=`date | cut -d ' ' -f4 | cut -d ':' -f3`

I="0"
ARGS=( "$@" )

for option in "${ARGS[@]}"; do
	I=`expr $I + 1`
	if [ "$option" == "-d" ]; then
		FD="${ARGS[$I]}/"
		for i in 1 2 3; do
			n=`expr $i + 1`
			d=`echo $FD | cut -d '/' -f$i`
			if [ "$d" == "Y" ]; then
				printf "$Y"
			elif [ "$d" == "M" ]; then
				printf "$M"
			else
				printf "$D"
			fi
			NEXT=`echo $FD | cut -d '/' -f$n`
			if [ "$NEXT" == "" ]; then
				if [ "`expr $I + 1`" -lt "$#" ]; then
					printf " "
				else
					echo ""
				fi
				break
			else
				printf "/"
			fi
		done
	elif [ "$option" == "-h" ]; then
		FH="${ARGS[$I]}:"
		for i in 1 2 3; do
			n=`expr $i + 1`
			d=`echo $FH | cut -d ':' -f$i`
			if [ "$d" == "H" ]; then
				printf "$H"
			elif [ "$d" == "M" ]; then
				printf "$Mi"
			else
				printf "$S"
			fi
			NEXT=`echo $FH | cut -d ':' -f$n`
			if [ "$NEXT" == "" ]; then
				if [ "`expr $I + 1`" -lt "$#" ]; then
					printf " "
				else
					echo ""
				fi
				break
			else
				printf ":"
			fi
		done
	fi
done
if [ "$1" == "" ]; then
	echo "Usage: gtime [-h | -d] <format>"
	echo "Exemple: gtime -d D/M/Y -h H:M"
fi
