#!/bin/bash

if [ "$1" == "-c" ]; then
	git add *
	git commit -m "$1"
fi

if [[ "$1" == "-p" || ("$1" == "-c" && "$3" == "-p") ]]; then
	git push origin master
fi

if [ "$3" == "-u" -a "$4" != "" -a "$5" != "" -a "$6" != "" ]; then
	git push https://$4:$5@github.com/$4/$6.git
elif [ "$3" == "-b" -a "$4" != "" ]; then
	git push -u origin $4
elif [ "$1" == "-h" ]; then
	echo "Description:"
	echo "rgit is a faster way to use very basics git fonctionnalities"
	echo ""
	echo "Options:"
	echo "-p	Push on origin master"
	echo "-c	Commit the changes as the specified title, require <commit_name>"
	echo "-u	Push into a repository as a specific user, require <account_pseudo> <account_password> <repository_name>"
	echo "-b	Push into a repository branch, require <branch_name>"
	echo "-h	Display the Help menu"
	echo ""
	echo "Exemple:"
	echo "rgit \"add parsing\" -u myPseudo xxxpsswdxxx myRepo"
	echo ""
	echo "this will commit all the modifications as \"add parsing\" and push it to the myRepo repository as myPseudo, using xxxpsswdxxx as password" 
else
	echo "Usage: rgit -p | -c <commit_name> [-c | -b | -u] <branch_name> | <account_pseudo> <account_password> <repository_name>"
	echo "Type: rgit -h to display the Help menu"
fi
